services:
  redis-server:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - spring-postgres
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=example
    links:
      - redis-server
    networks:
      - spring-postgres
  subscriber:
    build: subscriber
    ports:
      - 8081:8081
    environment:
      - POSTGRES_DB=example
    links:
      - redis-server
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - "5434:5432"
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  spring-postgres:
